<?php

namespace Wal3fo\PhoneCountry;

/**
 * Static country metadata keyed by ISO 3166-1 alpha-2 code.
 *
 * Each entry: [ name, flag, region, continent, capital, currency, currencyName, language, timezone ]
 *
 * The list covers all countries that appear in the prefix map.
 * Falls back to safe defaults for any unknown code.
 */
class CountryMetadata
{
    /** @return array{0:string,1:string,2:string,3:string,4:string,5:string,6:string,7:string,8:string} */
    public static function get(string $isoCode): array
    {
        return self::MAP[$isoCode] ?? ['Unknown', '🏳', 'Unknown', 'Unknown', 'Unknown', 'XXX', 'Unknown', 'Unknown', 'UTC'];
    }

    /**
     * @var array<string, array{0:string,1:string,2:string,3:string,4:string,5:string,6:string,7:string,8:string}>
     * Format: [name, flag, region, continent, capital, currency, currencyName, language, timezone]
     */
    private const MAP = [
        'AF' => ['Afghanistan',                   '🇦🇫', 'Southern Asia',      'Asia',    'Kabul',          'AFN', 'Afghan Afghani',       'Dari',            'Asia/Kabul'],
        'AL' => ['Albania',                        '🇦🇱', 'Southern Europe',    'Europe',  'Tirana',         'ALL', 'Albanian Lek',        'Albanian',        'Europe/Tirane'],
        'DZ' => ['Algeria',                        '🇩🇿', 'Northern Africa',    'Africa',  'Algiers',        'DZD', 'Algerian Dinar',      'Arabic',          'Africa/Algiers'],
        'AD' => ['Andorra',                        '🇦🇩', 'Southern Europe',    'Europe',  'Andorra la Vella','EUR','Euro',               'Catalan',         'Europe/Andorra'],
        'AO' => ['Angola',                         '🇦🇴', 'Middle Africa',      'Africa',  'Luanda',         'AOA', 'Angolan Kwanza',      'Portuguese',      'Africa/Luanda'],
        'AG' => ['Antigua and Barbuda',            '🇦🇬', 'Caribbean',          'Americas','Saint John\'s',  'XCD', 'East Caribbean Dollar','English',        'America/Antigua'],
        'AR' => ['Argentina',                      '🇦🇷', 'South America',      'Americas','Buenos Aires',   'ARS', 'Argentine Peso',      'Spanish',         'America/Argentina/Buenos_Aires'],
        'AM' => ['Armenia',                        '🇦🇲', 'Western Asia',       'Asia',    'Yerevan',        'AMD', 'Armenian Dram',       'Armenian',        'Asia/Yerevan'],
        'AU' => ['Australia',                      '🇦🇺', 'Oceania',            'Oceania', 'Canberra',       'AUD', 'Australian Dollar',   'English',         'Australia/Sydney'],
        'AT' => ['Austria',                        '🇦🇹', 'Western Europe',     'Europe',  'Vienna',         'EUR', 'Euro',                'German',          'Europe/Vienna'],
        'AZ' => ['Azerbaijan',                     '🇦🇿', 'Western Asia',       'Asia',    'Baku',           'AZN', 'Azerbaijani Manat',   'Azerbaijani',     'Asia/Baku'],
        'BS' => ['Bahamas',                        '🇧🇸', 'Caribbean',          'Americas','Nassau',         'BSD', 'Bahamian Dollar',     'English',         'America/Nassau'],
        'BH' => ['Bahrain',                        '🇧🇭', 'Western Asia',       'Asia',    'Manama',         'BHD', 'Bahraini Dinar',      'Arabic',          'Asia/Bahrain'],
        'BD' => ['Bangladesh',                     '🇧🇩', 'Southern Asia',      'Asia',    'Dhaka',          'BDT', 'Bangladeshi Taka',    'Bengali',         'Asia/Dhaka'],
        'BB' => ['Barbados',                       '🇧🇧', 'Caribbean',          'Americas','Bridgetown',     'BBD', 'Barbadian Dollar',    'English',         'America/Barbados'],
        'BY' => ['Belarus',                        '🇧🇾', 'Eastern Europe',     'Europe',  'Minsk',          'BYN', 'Belarusian Ruble',    'Belarusian',      'Europe/Minsk'],
        'BE' => ['Belgium',                        '🇧🇪', 'Western Europe',     'Europe',  'Brussels',       'EUR', 'Euro',                'Dutch',           'Europe/Brussels'],
        'BZ' => ['Belize',                         '🇧🇿', 'Central America',    'Americas','Belmopan',       'BZD', 'Belize Dollar',       'English',         'America/Belize'],
        'BJ' => ['Benin',                          '🇧🇯', 'Western Africa',     'Africa',  'Porto-Novo',     'XOF', 'CFA Franc BCEAO',     'French',          'Africa/Porto-Novo'],
        'BT' => ['Bhutan',                         '🇧🇹', 'Southern Asia',      'Asia',    'Thimphu',        'BTN', 'Bhutanese Ngultrum', 'Dzongkha',        'Asia/Thimphu'],
        'BO' => ['Bolivia',                        '🇧🇴', 'South America',      'Americas','Sucre',          'BOB', 'Bolivian Boliviano',  'Spanish',         'America/La_Paz'],
        'BA' => ['Bosnia and Herzegovina',         '🇧🇦', 'Southern Europe',    'Europe',  'Sarajevo',       'BAM', 'Bosnia-Herzegovina Convertible Mark','Bosnian','Europe/Sarajevo'],
        'BW' => ['Botswana',                       '🇧🇼', 'Southern Africa',    'Africa',  'Gaborone',       'BWP', 'Botswana Pula',       'English',         'Africa/Gaborone'],
        'BR' => ['Brazil',                         '🇧🇷', 'South America',      'Americas','Brasília',       'BRL', 'Brazilian Real',      'Portuguese',      'America/Sao_Paulo'],
        'BN' => ['Brunei',                         '🇧🇳', 'South-Eastern Asia', 'Asia',    'Bandar Seri Begawan','BND','Brunei Dollar',    'Malay',           'Asia/Brunei'],
        'BG' => ['Bulgaria',                       '🇧🇬', 'Eastern Europe',     'Europe',  'Sofia',          'BGN', 'Bulgarian Lev',       'Bulgarian',       'Europe/Sofia'],
        'BF' => ['Burkina Faso',                   '🇧🇫', 'Western Africa',     'Africa',  'Ouagadougou',    'XOF', 'CFA Franc BCEAO',     'French',          'Africa/Ouagadougou'],
        'BI' => ['Burundi',                        '🇧🇮', 'Eastern Africa',     'Africa',  'Bujumbura',      'BIF', 'Burundian Franc',     'Kirundi',         'Africa/Bujumbura'],
        'KH' => ['Cambodia',                       '🇰🇭', 'South-Eastern Asia', 'Asia',    'Phnom Penh',     'KHR', 'Cambodian Riel',      'Khmer',           'Asia/Phnom_Penh'],
        'CM' => ['Cameroon',                       '🇨🇲', 'Middle Africa',      'Africa',  'Yaoundé',        'XAF', 'CFA Franc BEAC',      'French',          'Africa/Douala'],
        'CA' => ['Canada',                         '🇨🇦', 'Northern America',   'Americas','Ottawa',         'CAD', 'Canadian Dollar',     'English',         'America/Toronto'],
        'CV' => ['Cape Verde',                     '🇨🇻', 'Western Africa',     'Africa',  'Praia',          'CVE', 'Cape Verdean Escudo', 'Portuguese',      'Atlantic/Cape_Verde'],
        'CF' => ['Central African Republic',       '🇨🇫', 'Middle Africa',      'Africa',  'Bangui',         'XAF', 'CFA Franc BEAC',      'Sango',           'Africa/Bangui'],
        'TD' => ['Chad',                           '🇹🇩', 'Middle Africa',      'Africa',  "N'Djamena",      'XAF', 'CFA Franc BEAC',      'Arabic',          'Africa/Ndjamena'],
        'CL' => ['Chile',                          '🇨🇱', 'South America',      'Americas','Santiago',       'CLP', 'Chilean Peso',        'Spanish',         'America/Santiago'],
        'CN' => ['China',                          '🇨🇳', 'Eastern Asia',       'Asia',    'Beijing',        'CNY', 'Chinese Yuan',        'Mandarin',        'Asia/Shanghai'],
        'CO' => ['Colombia',                       '🇨🇴', 'South America',      'Americas','Bogotá',         'COP', 'Colombian Peso',      'Spanish',         'America/Bogota'],
        'KM' => ['Comoros',                        '🇰🇲', 'Eastern Africa',     'Africa',  'Moroni',         'KMF', 'Comorian Franc',      'Comorian',        'Indian/Comoro'],
        'CG' => ['Congo',                          '🇨🇬', 'Middle Africa',      'Africa',  'Brazzaville',    'XAF', 'CFA Franc BEAC',      'French',          'Africa/Brazzaville'],
        'CD' => ['DR Congo',                       '🇨🇩', 'Middle Africa',      'Africa',  'Kinshasa',       'CDF', 'Congolese Franc',     'French',          'Africa/Kinshasa'],
        'CR' => ['Costa Rica',                     '🇨🇷', 'Central America',    'Americas','San José',       'CRC', 'Costa Rican Colón',   'Spanish',         'America/Costa_Rica'],
        'HR' => ['Croatia',                        '🇭🇷', 'Southern Europe',    'Europe',  'Zagreb',         'EUR', 'Euro',                'Croatian',        'Europe/Zagreb'],
        'CU' => ['Cuba',                           '🇨🇺', 'Caribbean',          'Americas','Havana',         'CUP', 'Cuban Peso',          'Spanish',         'America/Havana'],
        'CY' => ['Cyprus',                         '🇨🇾', 'Western Asia',       'Asia',    'Nicosia',        'EUR', 'Euro',                'Greek',           'Asia/Nicosia'],
        'CZ' => ['Czech Republic',                 '🇨🇿', 'Eastern Europe',     'Europe',  'Prague',         'CZK', 'Czech Koruna',        'Czech',           'Europe/Prague'],
        'DK' => ['Denmark',                        '🇩🇰', 'Northern Europe',    'Europe',  'Copenhagen',     'DKK', 'Danish Krone',        'Danish',          'Europe/Copenhagen'],
        'DJ' => ['Djibouti',                       '🇩🇯', 'Eastern Africa',     'Africa',  'Djibouti',       'DJF', 'Djiboutian Franc',    'Arabic',          'Africa/Djibouti'],
        'DM' => ['Dominica',                       '🇩🇲', 'Caribbean',          'Americas','Roseau',         'XCD', 'East Caribbean Dollar','English',        'America/Dominica'],
        'DO' => ['Dominican Republic',             '🇩🇴', 'Caribbean',          'Americas','Santo Domingo',  'DOP', 'Dominican Peso',      'Spanish',         'America/Santo_Domingo'],
        'EC' => ['Ecuador',                        '🇪🇨', 'South America',      'Americas','Quito',          'USD', 'US Dollar',           'Spanish',         'America/Guayaquil'],
        'EG' => ['Egypt',                          '🇪🇬', 'Northern Africa',    'Africa',  'Cairo',          'EGP', 'Egyptian Pound',      'Arabic',          'Africa/Cairo'],
        'SV' => ['El Salvador',                    '🇸🇻', 'Central America',    'Americas','San Salvador',   'USD', 'US Dollar',           'Spanish',         'America/El_Salvador'],
        'GQ' => ['Equatorial Guinea',              '🇬🇶', 'Middle Africa',      'Africa',  'Malabo',         'XAF', 'CFA Franc BEAC',      'Spanish',         'Africa/Malabo'],
        'ER' => ['Eritrea',                        '🇪🇷', 'Eastern Africa',     'Africa',  'Asmara',         'ERN', 'Eritrean Nakfa',      'Tigrinya',        'Africa/Asmara'],
        'EE' => ['Estonia',                        '🇪🇪', 'Northern Europe',    'Europe',  'Tallinn',        'EUR', 'Euro',                'Estonian',        'Europe/Tallinn'],
        'ET' => ['Ethiopia',                       '🇪🇹', 'Eastern Africa',     'Africa',  'Addis Ababa',    'ETB', 'Ethiopian Birr',      'Amharic',         'Africa/Addis_Ababa'],
        'FJ' => ['Fiji',                           '🇫🇯', 'Melanesia',          'Oceania', 'Suva',           'FJD', 'Fijian Dollar',       'English',         'Pacific/Fiji'],
        'FI' => ['Finland',                        '🇫🇮', 'Northern Europe',    'Europe',  'Helsinki',       'EUR', 'Euro',                'Finnish',         'Europe/Helsinki'],
        'FR' => ['France',                         '🇫🇷', 'Western Europe',     'Europe',  'Paris',          'EUR', 'Euro',                'French',          'Europe/Paris'],
        'GA' => ['Gabon',                          '🇬🇦', 'Middle Africa',      'Africa',  'Libreville',     'XAF', 'CFA Franc BEAC',      'French',          'Africa/Libreville'],
        'GM' => ['Gambia',                         '🇬🇲', 'Western Africa',     'Africa',  'Banjul',         'GMD', 'Gambian Dalasi',      'English',         'Africa/Banjul'],
        'GE' => ['Georgia',                        '🇬🇪', 'Western Asia',       'Asia',    'Tbilisi',        'GEL', 'Georgian Lari',       'Georgian',        'Asia/Tbilisi'],
        'DE' => ['Germany',                        '🇩🇪', 'Western Europe',     'Europe',  'Berlin',         'EUR', 'Euro',                'German',          'Europe/Berlin'],
        'GH' => ['Ghana',                          '🇬🇭', 'Western Africa',     'Africa',  'Accra',          'GHS', 'Ghanaian Cedi',       'English',         'Africa/Accra'],
        'GR' => ['Greece',                         '🇬🇷', 'Southern Europe',    'Europe',  'Athens',         'EUR', 'Euro',                'Greek',           'Europe/Athens'],
        'GD' => ['Grenada',                        '🇬🇩', 'Caribbean',          'Americas','Saint George\'s','XCD','East Caribbean Dollar','English',        'America/Grenada'],
        'GT' => ['Guatemala',                      '🇬🇹', 'Central America',    'Americas','Guatemala City', 'GTQ', 'Guatemalan Quetzal',  'Spanish',         'America/Guatemala'],
        'GN' => ['Guinea',                         '🇬🇳', 'Western Africa',     'Africa',  'Conakry',        'GNF', 'Guinean Franc',       'French',          'Africa/Conakry'],
        'GW' => ['Guinea-Bissau',                  '🇬🇼', 'Western Africa',     'Africa',  'Bissau',         'XOF', 'CFA Franc BCEAO',     'Portuguese',      'Africa/Bissau'],
        'GY' => ['Guyana',                         '🇬🇾', 'South America',      'Americas','Georgetown',     'GYD', 'Guyanese Dollar',     'English',         'America/Guyana'],
        'HT' => ['Haiti',                          '🇭🇹', 'Caribbean',          'Americas','Port-au-Prince', 'HTG', 'Haitian Gourde',      'Haitian Creole',  'America/Port-au-Prince'],
        'HN' => ['Honduras',                       '🇭🇳', 'Central America',    'Americas','Tegucigalpa',    'HNL', 'Honduran Lempira',    'Spanish',         'America/Tegucigalpa'],
        'HK' => ['Hong Kong',                      '🇭🇰', 'Eastern Asia',       'Asia',    'Hong Kong',      'HKD', 'Hong Kong Dollar',    'Chinese',         'Asia/Hong_Kong'],
        'HU' => ['Hungary',                        '🇭🇺', 'Eastern Europe',     'Europe',  'Budapest',       'HUF', 'Hungarian Forint',    'Hungarian',       'Europe/Budapest'],
        'IS' => ['Iceland',                        '🇮🇸', 'Northern Europe',    'Europe',  'Reykjavik',      'ISK', 'Icelandic Króna',     'Icelandic',       'Atlantic/Reykjavik'],
        'IN' => ['India',                          '🇮🇳', 'Southern Asia',      'Asia',    'New Delhi',      'INR', 'Indian Rupee',        'Hindi',           'Asia/Kolkata'],
        'ID' => ['Indonesia',                      '🇮🇩', 'South-Eastern Asia', 'Asia',    'Jakarta',        'IDR', 'Indonesian Rupiah',   'Indonesian',      'Asia/Jakarta'],
        'IR' => ['Iran',                           '🇮🇷', 'Southern Asia',      'Asia',    'Tehran',         'IRR', 'Iranian Rial',        'Persian',         'Asia/Tehran'],
        'IQ' => ['Iraq',                           '🇮🇶', 'Western Asia',       'Asia',    'Baghdad',        'IQD', 'Iraqi Dinar',         'Arabic',          'Asia/Baghdad'],
        'IE' => ['Ireland',                        '🇮🇪', 'Northern Europe',    'Europe',  'Dublin',         'EUR', 'Euro',                'English',         'Europe/Dublin'],
        'IL' => ['Israel',                         '🇮🇱', 'Western Asia',       'Asia',    'Jerusalem',      'ILS', 'Israeli Shekel',      'Hebrew',          'Asia/Jerusalem'],
        'IT' => ['Italy',                          '🇮🇹', 'Southern Europe',    'Europe',  'Rome',           'EUR', 'Euro',                'Italian',         'Europe/Rome'],
        'CI' => ['Ivory Coast',                    '🇨🇮', 'Western Africa',     'Africa',  'Yamoussoukro',   'XOF', 'CFA Franc BCEAO',     'French',          'Africa/Abidjan'],
        'JM' => ['Jamaica',                        '🇯🇲', 'Caribbean',          'Americas','Kingston',       'JMD', 'Jamaican Dollar',     'English',         'America/Jamaica'],
        'JP' => ['Japan',                          '🇯🇵', 'Eastern Asia',       'Asia',    'Tokyo',          'JPY', 'Japanese Yen',        'Japanese',        'Asia/Tokyo'],
        'JO' => ['Jordan',                         '🇯🇴', 'Western Asia',       'Asia',    'Amman',          'JOD', 'Jordanian Dinar',     'Arabic',          'Asia/Amman'],
        'KZ' => ['Kazakhstan',                     '🇰🇿', 'Central Asia',       'Asia',    'Nur-Sultan',     'KZT', 'Kazakhstani Tenge',   'Kazakh',          'Asia/Almaty'],
        'KE' => ['Kenya',                          '🇰🇪', 'Eastern Africa',     'Africa',  'Nairobi',        'KES', 'Kenyan Shilling',     'Swahili',         'Africa/Nairobi'],
        'KI' => ['Kiribati',                       '🇰🇮', 'Micronesia',         'Oceania', 'South Tarawa',   'AUD', 'Australian Dollar',   'English',         'Pacific/Tarawa'],
        'KW' => ['Kuwait',                         '🇰🇼', 'Western Asia',       'Asia',    'Kuwait City',    'KWD', 'Kuwaiti Dinar',       'Arabic',          'Asia/Kuwait'],
        'KG' => ['Kyrgyzstan',                     '🇰🇬', 'Central Asia',       'Asia',    'Bishkek',        'KGS', 'Kyrgyzstani Som',     'Kyrgyz',          'Asia/Bishkek'],
        'LA' => ['Laos',                           '🇱🇦', 'South-Eastern Asia', 'Asia',    'Vientiane',      'LAK', 'Lao Kip',             'Lao',             'Asia/Vientiane'],
        'LV' => ['Latvia',                         '🇱🇻', 'Northern Europe',    'Europe',  'Riga',           'EUR', 'Euro',                'Latvian',         'Europe/Riga'],
        'LB' => ['Lebanon',                        '🇱🇧', 'Western Asia',       'Asia',    'Beirut',         'LBP', 'Lebanese Pound',      'Arabic',          'Asia/Beirut'],
        'LS' => ['Lesotho',                        '🇱🇸', 'Southern Africa',    'Africa',  'Maseru',         'LSL', 'Lesotho Loti',        'Sesotho',         'Africa/Maseru'],
        'LR' => ['Liberia',                        '🇱🇷', 'Western Africa',     'Africa',  'Monrovia',       'LRD', 'Liberian Dollar',     'English',         'Africa/Monrovia'],
        'LY' => ['Libya',                          '🇱🇾', 'Northern Africa',    'Africa',  'Tripoli',        'LYD', 'Libyan Dinar',        'Arabic',          'Africa/Tripoli'],
        'LI' => ['Liechtenstein',                  '🇱🇮', 'Western Europe',     'Europe',  'Vaduz',          'CHF', 'Swiss Franc',         'German',          'Europe/Vaduz'],
        'LT' => ['Lithuania',                      '🇱🇹', 'Northern Europe',    'Europe',  'Vilnius',        'EUR', 'Euro',                'Lithuanian',      'Europe/Vilnius'],
        'LU' => ['Luxembourg',                     '🇱🇺', 'Western Europe',     'Europe',  'Luxembourg',     'EUR', 'Euro',                'Luxembourgish',   'Europe/Luxembourg'],
        'MO' => ['Macau',                          '🇲🇴', 'Eastern Asia',       'Asia',    'Macau',          'MOP', 'Macanese Pataca',     'Chinese',         'Asia/Macau'],
        'MG' => ['Madagascar',                     '🇲🇬', 'Eastern Africa',     'Africa',  'Antananarivo',   'MGA', 'Malagasy Ariary',     'Malagasy',        'Indian/Antananarivo'],
        'MW' => ['Malawi',                         '🇲🇼', 'Eastern Africa',     'Africa',  'Lilongwe',       'MWK', 'Malawian Kwacha',     'Chichewa',        'Africa/Blantyre'],
        'MY' => ['Malaysia',                       '🇲🇾', 'South-Eastern Asia', 'Asia',    'Kuala Lumpur',   'MYR', 'Malaysian Ringgit',   'Malay',           'Asia/Kuala_Lumpur'],
        'MV' => ['Maldives',                       '🇲🇻', 'Southern Asia',      'Asia',    'Malé',           'MVR', 'Maldivian Rufiyaa',   'Dhivehi',         'Indian/Maldives'],
        'ML' => ['Mali',                           '🇲🇱', 'Western Africa',     'Africa',  'Bamako',         'XOF', 'CFA Franc BCEAO',     'French',          'Africa/Bamako'],
        'MT' => ['Malta',                          '🇲🇹', 'Southern Europe',    'Europe',  'Valletta',       'EUR', 'Euro',                'Maltese',         'Europe/Malta'],
        'MH' => ['Marshall Islands',               '🇲🇭', 'Micronesia',         'Oceania', 'Majuro',         'USD', 'US Dollar',           'Marshallese',     'Pacific/Majuro'],
        'MR' => ['Mauritania',                     '🇲🇷', 'Western Africa',     'Africa',  'Nouakchott',     'MRU', 'Mauritanian Ouguiya', 'Arabic',          'Africa/Nouakchott'],
        'MU' => ['Mauritius',                      '🇲🇺', 'Eastern Africa',     'Africa',  'Port Louis',     'MUR', 'Mauritian Rupee',     'English',         'Indian/Mauritius'],
        'MX' => ['Mexico',                         '🇲🇽', 'Central America',    'Americas','Mexico City',    'MXN', 'Mexican Peso',        'Spanish',         'America/Mexico_City'],
        'FM' => ['Micronesia',                     '🇫🇲', 'Micronesia',         'Oceania', 'Palikir',        'USD', 'US Dollar',           'English',         'Pacific/Pohnpei'],
        'MD' => ['Moldova',                        '🇲🇩', 'Eastern Europe',     'Europe',  'Chișinău',       'MDL', 'Moldovan Leu',        'Romanian',        'Europe/Chisinau'],
        'MC' => ['Monaco',                         '🇲🇨', 'Western Europe',     'Europe',  'Monaco',         'EUR', 'Euro',                'French',          'Europe/Monaco'],
        'MN' => ['Mongolia',                       '🇲🇳', 'Eastern Asia',       'Asia',    'Ulaanbaatar',    'MNT', 'Mongolian Tögrög',   'Mongolian',       'Asia/Ulaanbaatar'],
        'ME' => ['Montenegro',                     '🇲🇪', 'Southern Europe',    'Europe',  'Podgorica',      'EUR', 'Euro',                'Montenegrin',     'Europe/Podgorica'],
        'MA' => ['Morocco',                        '🇲🇦', 'Northern Africa',    'Africa',  'Rabat',          'MAD', 'Moroccan Dirham',     'Arabic',          'Africa/Casablanca'],
        'MZ' => ['Mozambique',                     '🇲🇿', 'Eastern Africa',     'Africa',  'Maputo',         'MZN', 'Mozambican Metical',  'Portuguese',      'Africa/Maputo'],
        'MM' => ['Myanmar',                        '🇲🇲', 'South-Eastern Asia', 'Asia',    'Naypyidaw',      'MMK', 'Myanmar Kyat',        'Burmese',         'Asia/Rangoon'],
        'NA' => ['Namibia',                        '🇳🇦', 'Southern Africa',    'Africa',  'Windhoek',       'NAD', 'Namibian Dollar',     'English',         'Africa/Windhoek'],
        'NR' => ['Nauru',                          '🇳🇷', 'Micronesia',         'Oceania', 'Yaren',          'AUD', 'Australian Dollar',   'Nauruan',         'Pacific/Nauru'],
        'NP' => ['Nepal',                          '🇳🇵', 'Southern Asia',      'Asia',    'Kathmandu',      'NPR', 'Nepalese Rupee',      'Nepali',          'Asia/Kathmandu'],
        'NL' => ['Netherlands',                    '🇳🇱', 'Western Europe',     'Europe',  'Amsterdam',      'EUR', 'Euro',                'Dutch',           'Europe/Amsterdam'],
        'NZ' => ['New Zealand',                    '🇳🇿', 'Oceania',            'Oceania', 'Wellington',     'NZD', 'New Zealand Dollar',  'English',         'Pacific/Auckland'],
        'NI' => ['Nicaragua',                      '🇳🇮', 'Central America',    'Americas','Managua',        'NIO', 'Nicaraguan Córdoba',  'Spanish',         'America/Managua'],
        'NE' => ['Niger',                          '🇳🇪', 'Western Africa',     'Africa',  'Niamey',         'XOF', 'CFA Franc BCEAO',     'French',          'Africa/Niamey'],
        'NG' => ['Nigeria',                        '🇳🇬', 'Western Africa',     'Africa',  'Abuja',          'NGN', 'Nigerian Naira',      'English',         'Africa/Lagos'],
        'KP' => ['North Korea',                    '🇰🇵', 'Eastern Asia',       'Asia',    'Pyongyang',      'KPW', 'North Korean Won',    'Korean',          'Asia/Pyongyang'],
        'MK' => ['North Macedonia',                '🇲🇰', 'Southern Europe',    'Europe',  'Skopje',         'MKD', 'Macedonian Denar',    'Macedonian',      'Europe/Skopje'],
        'NO' => ['Norway',                         '🇳🇴', 'Northern Europe',    'Europe',  'Oslo',           'NOK', 'Norwegian Krone',     'Norwegian',       'Europe/Oslo'],
        'OM' => ['Oman',                           '🇴🇲', 'Western Asia',       'Asia',    'Muscat',         'OMR', 'Omani Rial',          'Arabic',          'Asia/Muscat'],
        'PK' => ['Pakistan',                       '🇵🇰', 'Southern Asia',      'Asia',    'Islamabad',      'PKR', 'Pakistani Rupee',     'Urdu',            'Asia/Karachi'],
        'PW' => ['Palau',                          '🇵🇼', 'Micronesia',         'Oceania', 'Ngerulmud',      'USD', 'US Dollar',           'Palauan',         'Pacific/Palau'],
        'PA' => ['Panama',                         '🇵🇦', 'Central America',    'Americas','Panama City',    'PAB', 'Panamanian Balboa',   'Spanish',         'America/Panama'],
        'PG' => ['Papua New Guinea',               '🇵🇬', 'Melanesia',          'Oceania', 'Port Moresby',   'PGK', 'Papua New Guinean Kina','English',        'Pacific/Port_Moresby'],
        'PY' => ['Paraguay',                       '🇵🇾', 'South America',      'Americas','Asunción',       'PYG', 'Paraguayan Guaraní', 'Spanish',         'America/Asuncion'],
        'PE' => ['Peru',                           '🇵🇪', 'South America',      'Americas','Lima',           'PEN', 'Peruvian Sol',        'Spanish',         'America/Lima'],
        'PH' => ['Philippines',                    '🇵🇭', 'South-Eastern Asia', 'Asia',    'Manila',         'PHP', 'Philippine Peso',     'Filipino',        'Asia/Manila'],
        'PL' => ['Poland',                         '🇵🇱', 'Eastern Europe',     'Europe',  'Warsaw',         'PLN', 'Polish Złoty',       'Polish',          'Europe/Warsaw'],
        'PT' => ['Portugal',                       '🇵🇹', 'Southern Europe',    'Europe',  'Lisbon',         'EUR', 'Euro',                'Portuguese',      'Europe/Lisbon'],
        'QA' => ['Qatar',                          '🇶🇦', 'Western Asia',       'Asia',    'Doha',           'QAR', 'Qatari Riyal',        'Arabic',          'Asia/Qatar'],
        'RO' => ['Romania',                        '🇷🇴', 'Eastern Europe',     'Europe',  'Bucharest',      'RON', 'Romanian Leu',        'Romanian',        'Europe/Bucharest'],
        'RU' => ['Russia',                         '🇷🇺', 'Eastern Europe',     'Europe',  'Moscow',         'RUB', 'Russian Ruble',       'Russian',         'Europe/Moscow'],
        'RW' => ['Rwanda',                         '🇷🇼', 'Eastern Africa',     'Africa',  'Kigali',         'RWF', 'Rwandan Franc',       'Kinyarwanda',     'Africa/Kigali'],
        'KN' => ['Saint Kitts and Nevis',          '🇰🇳', 'Caribbean',          'Americas','Basseterre',     'XCD', 'East Caribbean Dollar','English',        'America/St_Kitts'],
        'LC' => ['Saint Lucia',                    '🇱🇨', 'Caribbean',          'Americas','Castries',       'XCD', 'East Caribbean Dollar','English',        'America/St_Lucia'],
        'VC' => ['Saint Vincent and the Grenadines','🇻🇨','Caribbean',          'Americas','Kingstown',      'XCD', 'East Caribbean Dollar','English',        'America/St_Vincent'],
        'WS' => ['Samoa',                          '🇼🇸', 'Polynesia',          'Oceania', 'Apia',           'WST', 'Samoan Tālā',        'Samoan',          'Pacific/Apia'],
        'SM' => ['San Marino',                     '🇸🇲', 'Southern Europe',    'Europe',  'City of San Marino','EUR','Euro',             'Italian',         'Europe/San_Marino'],
        'ST' => ['São Tomé and Príncipe',          '🇸🇹', 'Middle Africa',      'Africa',  'São Tomé',       'STN', 'São Tomé and Príncipe Dobra','Portuguese','Africa/Sao_Tome'],
        'SA' => ['Saudi Arabia',                   '🇸🇦', 'Western Asia',       'Asia',    'Riyadh',         'SAR', 'Saudi Riyal',         'Arabic',          'Asia/Riyadh'],
        'SN' => ['Senegal',                        '🇸🇳', 'Western Africa',     'Africa',  'Dakar',          'XOF', 'CFA Franc BCEAO',     'French',          'Africa/Dakar'],
        'RS' => ['Serbia',                         '🇷🇸', 'Southern Europe',    'Europe',  'Belgrade',       'RSD', 'Serbian Dinar',       'Serbian',         'Europe/Belgrade'],
        'SC' => ['Seychelles',                     '🇸🇨', 'Eastern Africa',     'Africa',  'Victoria',       'SCR', 'Seychellois Rupee',   'Seychellois Creole','Indian/Mahe'],
        'SL' => ['Sierra Leone',                   '🇸🇱', 'Western Africa',     'Africa',  'Freetown',       'SLL', 'Sierra Leonean Leone','English',         'Africa/Freetown'],
        'SG' => ['Singapore',                      '🇸🇬', 'South-Eastern Asia', 'Asia',    'Singapore',      'SGD', 'Singapore Dollar',    'English',         'Asia/Singapore'],
        'SK' => ['Slovakia',                       '🇸🇰', 'Eastern Europe',     'Europe',  'Bratislava',     'EUR', 'Euro',                'Slovak',          'Europe/Bratislava'],
        'SI' => ['Slovenia',                       '🇸🇮', 'Southern Europe',    'Europe',  'Ljubljana',      'EUR', 'Euro',                'Slovenian',       'Europe/Ljubljana'],
        'SB' => ['Solomon Islands',                '🇸🇧', 'Melanesia',          'Oceania', 'Honiara',        'SBD', 'Solomon Islands Dollar','English',       'Pacific/Guadalcanal'],
        'SO' => ['Somalia',                        '🇸🇴', 'Eastern Africa',     'Africa',  'Mogadishu',      'SOS', 'Somali Shilling',     'Somali',          'Africa/Mogadishu'],
        'ZA' => ['South Africa',                   '🇿🇦', 'Southern Africa',    'Africa',  'Pretoria',       'ZAR', 'South African Rand',  'Zulu',            'Africa/Johannesburg'],
        'KR' => ['South Korea',                    '🇰🇷', 'Eastern Asia',       'Asia',    'Seoul',          'KRW', 'South Korean Won',    'Korean',          'Asia/Seoul'],
        'SS' => ['South Sudan',                    '🇸🇸', 'Eastern Africa',     'Africa',  'Juba',           'SSP', 'South Sudanese Pound','English',         'Africa/Juba'],
        'ES' => ['Spain',                          '🇪🇸', 'Southern Europe',    'Europe',  'Madrid',         'EUR', 'Euro',                'Spanish',         'Europe/Madrid'],
        'LK' => ['Sri Lanka',                      '🇱🇰', 'Southern Asia',      'Asia',    'Sri Jayawardenepura Kotte','LKR','Sri Lankan Rupee','Sinhala',  'Asia/Colombo'],
        'SD' => ['Sudan',                          '🇸🇩', 'Northern Africa',    'Africa',  'Khartoum',       'SDG', 'Sudanese Pound',      'Arabic',          'Africa/Khartoum'],
        'SR' => ['Suriname',                       '🇸🇷', 'South America',      'Americas','Paramaribo',     'SRD', 'Surinamese Dollar',   'Dutch',           'America/Paramaribo'],
        'SZ' => ['Eswatini',                       '🇸🇿', 'Southern Africa',    'Africa',  'Mbabane',        'SZL', 'Swazi Lilangeni',     'Swati',           'Africa/Mbabane'],
        'SE' => ['Sweden',                         '🇸🇪', 'Northern Europe',    'Europe',  'Stockholm',      'SEK', 'Swedish Krona',       'Swedish',         'Europe/Stockholm'],
        'CH' => ['Switzerland',                    '🇨🇭', 'Western Europe',     'Europe',  'Bern',           'CHF', 'Swiss Franc',         'German',          'Europe/Zurich'],
        'SY' => ['Syria',                          '🇸🇾', 'Western Asia',       'Asia',    'Damascus',       'SYP', 'Syrian Pound',        'Arabic',          'Asia/Damascus'],
        'TW' => ['Taiwan',                         '🇹🇼', 'Eastern Asia',       'Asia',    'Taipei',         'TWD', 'New Taiwan Dollar',   'Mandarin',        'Asia/Taipei'],
        'TJ' => ['Tajikistan',                     '🇹🇯', 'Central Asia',       'Asia',    'Dushanbe',       'TJS', 'Tajikistani Somoni',  'Tajik',           'Asia/Dushanbe'],
        'TZ' => ['Tanzania',                       '🇹🇿', 'Eastern Africa',     'Africa',  'Dodoma',         'TZS', 'Tanzanian Shilling',  'Swahili',         'Africa/Dar_es_Salaam'],
        'TH' => ['Thailand',                       '🇹🇭', 'South-Eastern Asia', 'Asia',    'Bangkok',        'THB', 'Thai Baht',           'Thai',            'Asia/Bangkok'],
        'TL' => ['Timor-Leste',                    '🇹🇱', 'South-Eastern Asia', 'Asia',    'Dili',           'USD', 'US Dollar',           'Tetum',           'Asia/Dili'],
        'TG' => ['Togo',                           '🇹🇬', 'Western Africa',     'Africa',  'Lomé',           'XOF', 'CFA Franc BCEAO',     'French',          'Africa/Lome'],
        'TO' => ['Tonga',                          '🇹🇴', 'Polynesia',          'Oceania', "Nuku'alofa",     'TOP', "Tongan Pa'anga",       'Tongan',          'Pacific/Tongatapu'],
        'TT' => ['Trinidad and Tobago',            '🇹🇹', 'Caribbean',          'Americas','Port of Spain',  'TTD', 'Trinidad and Tobago Dollar','English',   'America/Port_of_Spain'],
        'TN' => ['Tunisia',                        '🇹🇳', 'Northern Africa',    'Africa',  'Tunis',          'TND', 'Tunisian Dinar',      'Arabic',          'Africa/Tunis'],
        'TR' => ['Turkey',                         '🇹🇷', 'Western Asia',       'Asia',    'Ankara',         'TRY', 'Turkish Lira',        'Turkish',         'Europe/Istanbul'],
        'TM' => ['Turkmenistan',                   '🇹🇲', 'Central Asia',       'Asia',    'Ashgabat',       'TMT', 'Turkmenistani Manat', 'Turkmen',         'Asia/Ashgabat'],
        'TV' => ['Tuvalu',                         '🇹🇻', 'Polynesia',          'Oceania', 'Funafuti',       'AUD', 'Australian Dollar',   'Tuvaluan',        'Pacific/Funafuti'],
        'UG' => ['Uganda',                         '🇺🇬', 'Eastern Africa',     'Africa',  'Kampala',        'UGX', 'Ugandan Shilling',    'Swahili',         'Africa/Kampala'],
        'UA' => ['Ukraine',                        '🇺🇦', 'Eastern Europe',     'Europe',  'Kyiv',           'UAH', 'Ukrainian Hryvnia',   'Ukrainian',       'Europe/Kiev'],
        'AE' => ['United Arab Emirates',           '🇦🇪', 'Western Asia',       'Asia',    'Abu Dhabi',      'AED', 'UAE Dirham',          'Arabic',          'Asia/Dubai'],
        'GB' => ['United Kingdom',                 '🇬🇧', 'Northern Europe',    'Europe',  'London',         'GBP', 'British Pound',       'English',         'Europe/London'],
        'US' => ['United States',                  '🇺🇸', 'Northern America',   'Americas','Washington D.C.','USD','US Dollar',           'English',         'America/New_York'],
        'UY' => ['Uruguay',                        '🇺🇾', 'South America',      'Americas','Montevideo',     'UYU', 'Uruguayan Peso',      'Spanish',         'America/Montevideo'],
        'UZ' => ['Uzbekistan',                     '🇺🇿', 'Central Asia',       'Asia',    'Tashkent',       'UZS', 'Uzbekistani Som',     'Uzbek',           'Asia/Tashkent'],
        'VU' => ['Vanuatu',                        '🇻🇺', 'Melanesia',          'Oceania', 'Port Vila',      'VUV', 'Vanuatu Vatu',        'Bislama',         'Pacific/Efate'],
        'VE' => ['Venezuela',                      '🇻🇪', 'South America',      'Americas','Caracas',        'VES', 'Venezuelan Bolívar', 'Spanish',         'America/Caracas'],
        'VN' => ['Vietnam',                        '🇻🇳', 'South-Eastern Asia', 'Asia',    'Hanoi',          'VND', 'Vietnamese Dong',     'Vietnamese',      'Asia/Ho_Chi_Minh'],
        'YE' => ['Yemen',                          '🇾🇪', 'Western Asia',       'Asia',    "Sana'a",         'YER', 'Yemeni Rial',         'Arabic',          'Asia/Aden'],
        'ZM' => ['Zambia',                         '🇿🇲', 'Eastern Africa',     'Africa',  'Lusaka',         'ZMW', 'Zambian Kwacha',      'English',         'Africa/Lusaka'],
        'ZW' => ['Zimbabwe',                       '🇿🇼', 'Eastern Africa',     'Africa',  'Harare',         'ZWL', 'Zimbabwean Dollar',   'Shona',           'Africa/Harare'],
        'XX' => ['Unknown',                        '🏳',  'Unknown',            'Unknown', 'Unknown',        'XXX', 'Unknown',             'Unknown',         'UTC'],
    ];
}
